### ISSUE TITLE
Add filtering templates

### ISSUE THREAD

**Issue by sergey-trukhin** [sergey-trukhin/sshcld#13]
**Type**: feature request

**Feature description**:
As a user I would like to save frequently used filters in the `sshcld.yaml` file. Maybe something like this:
```yaml
filter_templates:
  prod:
    default_cloud: aws
    cloud_profile: production
    cloud_region: us-east-1
    printable_tags:
      - environment
      - department
    default_filter: "production,department=marketing"
```

Then I can use something like this:
```
sshcld -t prod
```

Please note that there is no feature for `default_filter` parameter yet. It should be implemented in #12
